"""create vehicles table

Revision ID: bbed2901bae4
Revises: 2f3150a0c766
Create Date: 2026-05-10 10:13:58.108572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbed2901bae4'
down_revision: Union[str, None] = '2f3150a0c766'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('make', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('license_plate', sa.String(length=30), nullable=False),
    sa.Column('category', sa.Enum('economy', 'standard', 'premium', 'suv', 'van', name='vehiclecategory'), nullable=False),
    sa.Column('daily_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fuel_type', sa.Enum('petrol', 'diesel', 'electric', 'hybrid', name='fueltype'), nullable=True),
    sa.Column('seats', sa.SmallInteger(), nullable=True),
    sa.Column('status', sa.Enum('available', 'booked', 'maintenance', name='vehiclestatus'), server_default='available', nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_plate')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicles')
    # ### end Alembic commands ###
